package cli

import (
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"

	promptkit "github.com/Sumatoshi-tech/promptkit"
	"github.com/Sumatoshi-tech/promptkit/internal/config"
	"github.com/Sumatoshi-tech/promptkit/internal/scaffold"
)

var cleanFlags struct {
	yes    bool
	dryRun bool
}

func init() {
	cleanCmd.Flags().BoolVarP(&cleanFlags.yes, "yes", "y", false, "auto-approve removal")
	cleanCmd.Flags().BoolVar(&cleanFlags.dryRun, "dry-run", false, "list stale files without removing")

	rootCmd.AddCommand(cleanCmd)
}

var cleanCmd = &cobra.Command{
	Use:   "clean",
	Short: "Remove stale generated files",
	Long: `Detects and removes files that were previously generated by promptkit
but are no longer produced by the current config. This happens when you
remove an agent or change settings that reduce the file set.

Use --dry-run to preview what would be removed.`,
	RunE: runClean,
}

func runClean(_ *cobra.Command, _ []string) error {
	dir, err := resolveConfigDir()
	if err != nil {
		return err
	}

	cfg, err := config.Load(dir)
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}

	rendered, err := scaffold.RenderFullWithOverrides(cfg, promptkit.Templates, cfg.TemplateOver)
	if err != nil {
		return fmt.Errorf("rendering templates: %w", err)
	}

	stale := scaffold.DetectStale(rendered, cfg.GeneratedFiles)

	if len(stale) == 0 {
		fmt.Println("No stale files.")
		return nil
	}

	fmt.Printf("Found %d stale file(s):\n", len(stale))

	for _, s := range stale {
		fmt.Printf("  - %s\n", s)
	}

	if cleanFlags.dryRun {
		fmt.Println("\nDry run — no files were removed.")
		return nil
	}

	if !cleanFlags.yes {
		fmt.Fprint(os.Stdout, "\nRemove these files? [y/N] ")

		var answer string

		_, _ = fmt.Fscanln(os.Stdin, &answer)

		if !strings.EqualFold(answer, "y") {
			fmt.Println("Aborted.")
			return nil
		}
	}

	if err = scaffold.RemoveFiles(dir, stale); err != nil {
		return fmt.Errorf("removing stale files: %w", err)
	}

	// Update manifest.
	cfg.GeneratedFiles = scaffold.FileManifest(rendered)

	if err = config.Save(cfg, dir); err != nil {
		return fmt.Errorf("saving config: %w", err)
	}

	fmt.Printf("Removed %d stale file(s).\n", len(stale))

	return nil
}
