// Package adapters maps rendered templates to agent-specific file placements.
package adapters

import (
	"fmt"
	"path/filepath"

	"github.com/Sumatoshi-tech/prompts/internal/config"
)

// SkillDef defines a skill extracted from rendered instruction templates.
type SkillDef struct {
	Name        string // Skill name (e.g. "implement").
	Description string // Short description for frontmatter.
	Body        []byte // Rendered markdown body (instruction content).
}

// PlacedFile represents a file to be written at a specific path.
type PlacedFile struct {
	Path    string // Relative path from project root.
	Content []byte
}

// AgentInstructionsDir is the project-relative directory for rendered instruction
// sources (skill bodies and workflow templates).
const AgentInstructionsDir = ".agents/instructions"

// InstrFRDPath is the on-disk FRD outline used by the implement workflow.
const InstrFRDPath = AgentInstructionsDir + "/instr-frd.md"

// InstrJourneyPath is the on-disk journey outline used by the implement workflow.
const InstrJourneyPath = AgentInstructionsDir + "/instr-journey.md"

// Workflow templates (FRD / journey) stay on disk under AgentInstructionsDir;
// they are not Agent Skills. /implement tells the agent to copy and fill them.

// baseSkills are skills present in all workflows.
var baseSkills = map[string]SkillDef{
	AgentInstructionsDir + "/instr-implement.md": {
		Name:        "implement",
		Description: "Iterative TDD implementation following roadmap items",
	},
	AgentInstructionsDir + "/instr-roadmaper.md": {
		Name:        "roadmap",
		Description: "Create decomposed roadmap from specification",
	},
	AgentInstructionsDir + "/instr-perf.md": {
		Name:        "perf",
		Description: "Performance diagnosis and optimization workflow",
	},
}

// skillInstructionPaths lists raw instruction files that are converted into
// Agent Skills and therefore removed from the rendered tree after placement.
func skillInstructionPaths() map[string]bool {
	paths := make(map[string]bool, len(baseSkills))
	for path := range baseSkills {
		paths[path] = true
	}

	return paths
}

// PlaceForAgents takes the rendered template output and generates
// agent-specific file placements for all configured agents.
// Skill-backed instruction files (implement, roadmap, perf) are deleted from
// the output map by the caller after placement; workflow templates under
// AgentInstructionsDir (FRD or journey) are left on disk.
func PlaceForAgents(rendered map[string][]byte, agents []string) ([]PlacedFile, error) {
	// Extract skill bodies from rendered instructions.
	extractedSkills := extractSkills(rendered)

	var placed []PlacedFile

	for _, agent := range agents {
		files, err := placeForAgent(agent, extractedSkills, rendered)
		if err != nil {
			return nil, fmt.Errorf("placing for agent %s: %w", agent, err)
		}

		placed = append(placed, files...)
	}

	return placed, nil
}

// FileAgent describes the agent ownership of a generated file.
type FileAgent struct {
	Path     string   // Relative path from project root.
	Agents   []string // Agent(s) that generate this file (nil for base files).
	IsShared bool     // True if generated by multiple agents.
}

// FileOwnership computes a reverse mapping from file paths to the agents
// that generate them. Base template files (AGENTS.md, Makefile, etc.)
// have nil Agents. Files produced by multiple agents are marked IsShared.
func FileOwnership(rendered map[string][]byte, agents []string) (map[string]FileAgent, error) {
	extractedSkills := extractSkills(rendered)
	ownership := make(map[string]FileAgent)

	// Base template files (not produced by any agent).
	instrPaths := make(map[string]bool)
	for _, p := range RemoveInstructionPaths() {
		instrPaths[p] = true
	}

	for path := range rendered {
		if instrPaths[path] {
			continue // raw instructions are removed; skip.
		}

		ownership[path] = FileAgent{Path: path}
	}

	// Agent-specific files.
	for _, agent := range agents {
		files, err := placeForAgent(agent, extractedSkills, rendered)
		if err != nil {
			return nil, fmt.Errorf("computing ownership for %s: %w", agent, err)
		}

		for _, f := range files {
			existing, ok := ownership[f.Path]
			if !ok {
				existing = FileAgent{Path: f.Path}
			}

			existing.Agents = append(existing.Agents, agent)
			ownership[f.Path] = existing
		}
	}

	// Mark shared files.
	for path, fa := range ownership {
		if len(fa.Agents) > 1 {
			fa.IsShared = true
			ownership[path] = fa
		}
	}

	return ownership, nil
}

// RemoveInstructionPaths returns raw instruction paths removed after skill
// placement. Workflow templates (instr-frd.md, instr-journey.md) are not
// included — they remain under AgentInstructionsDir for /implement to follow.
func RemoveInstructionPaths() []string {
	paths := skillInstructionPaths()
	out := make([]string, 0, len(paths))

	for path := range paths {
		out = append(out, path)
	}

	return out
}

func extractSkills(rendered map[string][]byte) []SkillDef {
	var result []SkillDef

	for path, def := range baseSkills {
		body, ok := rendered[path]
		if !ok {
			continue
		}

		result = append(result, SkillDef{
			Name:        def.Name,
			Description: def.Description,
			Body:        body,
		})
	}

	return result
}

func placeForAgent(agent string, extractedSkills []SkillDef, rendered map[string][]byte) ([]PlacedFile, error) {
	switch agent {
	case config.AgentClaude:
		return placeClaude(extractedSkills, rendered)
	case config.AgentCodex:
		return placeCodex(extractedSkills, rendered)
	case config.AgentCopilot:
		return placeCopilot(extractedSkills, rendered)
	case config.AgentCursor:
		return placeCursor(extractedSkills, rendered)
	case config.AgentGemini:
		return placeGemini(extractedSkills, rendered)
	case config.AgentWindsurf:
		return placeWindsurf(extractedSkills, rendered)
	default:
		return nil, fmt.Errorf("unknown agent: %s", agent)
	}
}

// skillMD wraps a skill body with Agent Skills SKILL.md frontmatter.
func skillMD(skill SkillDef) []byte {
	// Pre-compute exact size to avoid Builder reallocations.
	header := "---\nname: " + skill.Name + "\ndescription: " + skill.Description + "\n---\n\n"
	buf := make([]byte, len(header)+len(skill.Body))
	copy(buf, header)
	copy(buf[len(header):], skill.Body)

	return buf
}

// placeClaude generates:
//   - .agents/skills/<name>/SKILL.md  (Agent Skills standard — cross-agent)
//   - .claude/commands/<name>.md       (Claude Code slash commands — legacy compat)
func placeClaude(skills []SkillDef, _ map[string][]byte) ([]PlacedFile, error) {
	// Each skill produces 2 files: .agents/skills/ + .claude/commands/.
	filesPerSkill := 2
	files := make([]PlacedFile, 0, filesPerSkill*len(skills))

	for _, skill := range skills {
		// Agent Skills standard path (works across Claude, Codex, Copilot, Cursor).
		// Claude-specific legacy commands for backward compatibility.
		files = append(files, PlacedFile{
			Path:    filepath.Join(".agents", "skills", skill.Name, "SKILL.md"),
			Content: skillMD(skill),
		}, PlacedFile{
			Path:    filepath.Join(".claude", "commands", skill.Name+".md"),
			Content: skillMD(skill),
		})
	}

	return files, nil
}

// placeCodex generates:
//   - .agents/skills/<name>/SKILL.md  (Agent Skills standard)
func placeCodex(skills []SkillDef, _ map[string][]byte) ([]PlacedFile, error) {
	files := make([]PlacedFile, 0, len(skills))

	for _, skill := range skills {
		files = append(files, PlacedFile{
			Path:    filepath.Join(".agents", "skills", skill.Name, "SKILL.md"),
			Content: skillMD(skill),
		})
	}

	// Codex also reads AGENTS.md natively — no extra placement needed.
	return files, nil
}

// placeCopilot generates:
//   - .agents/skills/<name>/SKILL.md     (Agent Skills standard — Copilot discovers these)
//   - .github/copilot-instructions.md     (Copilot global instructions)
func placeCopilot(skills []SkillDef, rendered map[string][]byte) ([]PlacedFile, error) {
	var files []PlacedFile

	for _, skill := range skills {
		files = append(files, PlacedFile{
			Path:    filepath.Join(".agents", "skills", skill.Name, "SKILL.md"),
			Content: skillMD(skill),
		})
	}

	// Copilot reads a global instructions file.
	if agents, ok := rendered["AGENTS.md"]; ok {
		files = append(files, PlacedFile{
			Path:    filepath.Join(".github", "copilot-instructions.md"),
			Content: agents,
		})
	}

	return files, nil
}

// placeCursor generates:
//   - .agents/skills/<name>/SKILL.md   (Agent Skills standard — Cursor discovers these)
//   - .cursor/rules/agents.mdc          (Cursor rules file from AGENTS.md)
func placeCursor(skills []SkillDef, rendered map[string][]byte) ([]PlacedFile, error) {
	var files []PlacedFile

	for _, skill := range skills {
		files = append(files, PlacedFile{
			Path:    filepath.Join(".agents", "skills", skill.Name, "SKILL.md"),
			Content: skillMD(skill),
		})
	}

	// Cursor reads .cursor/rules/*.mdc with MDC frontmatter.
	if agents, ok := rendered["AGENTS.md"]; ok {
		mdc := wrapMDC("Golang coding agent personality and development workflow", "**/*.go", agents)
		files = append(files, PlacedFile{
			Path:    filepath.Join(".cursor", "rules", "agents.mdc"),
			Content: mdc,
		})
	}

	return files, nil
}

// placeGemini generates:
//   - GEMINI.md                              (Gemini global instructions)
//   - .gemini/commands/<name>.toml            (Gemini TOML commands)
func placeGemini(skills []SkillDef, rendered map[string][]byte) ([]PlacedFile, error) {
	var files []PlacedFile

	// Gemini reads GEMINI.md as its instructions file.
	if agents, ok := rendered["AGENTS.md"]; ok {
		files = append(files, PlacedFile{
			Path:    "GEMINI.md",
			Content: agents,
		})
	}

	// Gemini uses TOML commands, not Markdown.
	for _, skill := range skills {
		toml := skillTOML(skill)
		files = append(files, PlacedFile{
			Path:    filepath.Join(".gemini", "commands", skill.Name+".toml"),
			Content: toml,
		})
	}

	return files, nil
}

// placeWindsurf generates:
//   - .windsurfrules                           (Windsurf global rules from AGENTS.md)
//   - .windsurf/workflows/<name>.md             (Windsurf workflows)
func placeWindsurf(skills []SkillDef, rendered map[string][]byte) ([]PlacedFile, error) {
	var files []PlacedFile

	// Windsurf reads .windsurfrules as its instructions.
	if agents, ok := rendered["AGENTS.md"]; ok {
		files = append(files, PlacedFile{
			Path:    ".windsurfrules",
			Content: agents,
		})
	}

	// Windsurf uses .windsurf/workflows/*.md.
	for _, skill := range skills {
		files = append(files, PlacedFile{
			Path:    filepath.Join(".windsurf", "workflows", skill.Name+".md"),
			Content: skill.Body,
		})
	}

	return files, nil
}

// wrapMDC wraps content in Cursor's MDC format with frontmatter.
func wrapMDC(description, globs string, body []byte) []byte {
	header := "---\ndescription: " + description + "\nglobs: [\"" + globs + "\"]\nalwaysApply: true\n---\n\n"
	buf := make([]byte, len(header)+len(body))
	copy(buf, header)
	copy(buf[len(header):], body)

	return buf
}

// skillTOML converts a skill to Gemini CLI's TOML command format.
func skillTOML(skill SkillDef) []byte {
	descLine := fmt.Sprintf("description = %q\n", skill.Description)

	const (
		prefix = "prompt = \"\"\"\n"
		suffix = "\"\"\"\n"
	)

	needsNewline := len(skill.Body) > 0 && skill.Body[len(skill.Body)-1] != '\n'

	extra := 0
	if needsNewline {
		extra = 1
	}

	capacity := len(descLine) + len(prefix) + len(skill.Body) + extra + len(suffix)
	buf := make([]byte, 0, capacity)
	buf = append(buf, descLine...)
	buf = append(buf, prefix...)
	buf = append(buf, skill.Body...)

	if needsNewline {
		buf = append(buf, '\n')
	}

	buf = append(buf, suffix...)

	return buf
}
