// Package adapters maps rendered templates to agent-specific file placements.
package adapters

import (
	"fmt"
	"io/fs"
	"maps"
	"path/filepath"

	"github.com/Sumatoshi-tech/prompts/internal/config"
	"github.com/Sumatoshi-tech/prompts/internal/mixtures"
)

// SkillDef defines a skill extracted from rendered instruction templates.
type SkillDef struct {
	Name        string // Skill name (e.g. "implement").
	Description string // Short description for frontmatter.
	Body        []byte // Rendered markdown body (instruction content).
}

// PlacedFile represents a file to be written at a specific path.
type PlacedFile struct {
	Path    string // Relative path from project root.
	Content []byte
}

// baseSkills are skills present in all workflows.
var baseSkills = map[string]SkillDef{
	"instructions/instr-implement.md": {
		Name:        "implement",
		Description: "Iterative TDD implementation following roadmap items",
	},
	"instructions/instr-roadmaper.md": {
		Name:        "roadmap",
		Description: "Create decomposed roadmap from specification",
	},
	"instructions/instr-perf.md": {
		Name:        "perf",
		Description: "Performance diagnosis and optimization workflow",
	},
	"instructions/instr-generalize.md": {
		Name:        "generalize",
		Description: "Find reusable code and document generalization opportunities",
	},
	"instructions/instr-bug.md": {
		Name:        "bug",
		Description: "Systematic bug diagnosis and test-driven fix workflow",
	},
	"instructions/instr-researcher.md": {
		Name:        "researcher",
		Description: "Technical product research and specification workflow",
	},
}

// workflowSkills maps workflow name to the workflow-specific skill.
var workflowSkills = map[string]map[string]SkillDef{
	config.WorkflowFRD: {
		"instructions/instr-frd.md": {
			Name:        "frd",
			Description: "Feature requirements document template",
		},
	},
	config.WorkflowJourney: {
		"instructions/instr-journey.md": {
			Name:        "journey",
			Description: "Journey-based feature requirements with CJM",
		},
	},
}

// skillsForWorkflow returns the combined skill map for a given workflow.
func skillsForWorkflow(workflow string) map[string]SkillDef {
	result := make(map[string]SkillDef, len(baseSkills)+1)
	maps.Copy(result, baseSkills)

	if wfSkills, ok := workflowSkills[workflow]; ok {
		maps.Copy(result, wfSkills)
	} else {
		// Default to FRD workflow.
		maps.Copy(result, workflowSkills[config.WorkflowFRD])
	}

	return result
}

// allSkillPaths returns all possible instruction paths across all workflows.
func allSkillPaths() map[string]bool {
	paths := make(map[string]bool)
	for path := range baseSkills {
		paths[path] = true
	}

	for _, wfSkills := range workflowSkills {
		for path := range wfSkills {
			paths[path] = true
		}
	}

	return paths
}

// MixtureOpts holds parameters for mixture injection during skill extraction.
// When TemplateFS is nil, mixture injection is skipped.
type MixtureOpts struct {
	Active     []string       // Active mixture names from config.
	TemplateFS fs.FS          // Embedded template filesystem.
	Ecosystem  string         // Current ecosystem (e.g. "golang").
	Config     *config.Config // Full config for template rendering.
}

// PlaceForAgents takes the rendered template output and generates
// agent-specific file placements for all configured agents.
// It also removes the raw instructions/ files from the output since
// they are replaced by agent-specific skill files.
func PlaceForAgents(rendered map[string][]byte, agents []string, workflow string, mix *MixtureOpts) ([]PlacedFile, error) {
	// Extract skill bodies from rendered instructions.
	extractedSkills, err := extractSkills(rendered, workflow, mix)
	if err != nil {
		return nil, fmt.Errorf("extracting skills: %w", err)
	}

	var placed []PlacedFile

	for _, agent := range agents {
		files, placeErr := placeForAgent(agent, extractedSkills, rendered)
		if placeErr != nil {
			return nil, fmt.Errorf("placing for agent %s: %w", agent, placeErr)
		}

		placed = append(placed, files...)
	}

	return placed, nil
}

// FileAgent describes the agent ownership of a generated file.
type FileAgent struct {
	Path     string   // Relative path from project root.
	Agents   []string // Agent(s) that generate this file (nil for base files).
	IsShared bool     // True if generated by multiple agents.
}

// FileOwnership computes a reverse mapping from file paths to the agents
// that generate them. Base template files (AGENTS.md, Makefile, etc.)
// have nil Agents. Files produced by multiple agents are marked IsShared.
func FileOwnership(rendered map[string][]byte, agents []string, workflow string) (map[string]FileAgent, error) {
	extractedSkills, err := extractSkills(rendered, workflow, nil)
	if err != nil {
		return nil, fmt.Errorf("extracting skills: %w", err)
	}

	ownership := buildBaseOwnership(rendered)

	if addErr := addAgentOwnership(ownership, agents, extractedSkills, rendered); addErr != nil {
		return nil, addErr
	}

	markSharedFiles(ownership)

	return ownership, nil
}

func buildBaseOwnership(rendered map[string][]byte) map[string]FileAgent {
	ownership := make(map[string]FileAgent)

	instrPaths := make(map[string]bool)
	for _, p := range RemoveInstructionPaths() {
		instrPaths[p] = true
	}

	for path := range rendered {
		if instrPaths[path] {
			continue
		}

		ownership[path] = FileAgent{Path: path}
	}

	return ownership
}

func addAgentOwnership(ownership map[string]FileAgent, agents []string, skills []SkillDef, rendered map[string][]byte) error {
	for _, agent := range agents {
		files, err := placeForAgent(agent, skills, rendered)
		if err != nil {
			return fmt.Errorf("computing ownership for %s: %w", agent, err)
		}

		for _, f := range files {
			existing, ok := ownership[f.Path]
			if !ok {
				existing = FileAgent{Path: f.Path}
			}

			existing.Agents = append(existing.Agents, agent)
			ownership[f.Path] = existing
		}
	}

	return nil
}

func markSharedFiles(ownership map[string]FileAgent) {
	for path, fa := range ownership {
		if len(fa.Agents) > 1 {
			fa.IsShared = true
			ownership[path] = fa
		}
	}
}

// RemoveInstructionPaths returns the set of raw instruction paths that
// should be removed from the rendered output (they are replaced by skills).
// Returns all possible instruction paths across all workflows.
func RemoveInstructionPaths() []string {
	allPaths := allSkillPaths()
	paths := make([]string, 0, len(allPaths))

	for path := range allPaths {
		paths = append(paths, path)
	}

	return paths
}

func extractSkills(rendered map[string][]byte, workflow string, mix *MixtureOpts) ([]SkillDef, error) {
	var result []SkillDef

	for path, def := range skillsForWorkflow(workflow) {
		body, ok := rendered[path]
		if !ok {
			continue
		}

		// Inject mixture content if configured.
		if mix != nil && len(mix.Active) > 0 && mix.TemplateFS != nil {
			injected, err := mixtures.AppendToSkill(body, mix.TemplateFS, mix.Ecosystem, mix.Active, def.Name, mix.Config)
			if err != nil {
				return nil, fmt.Errorf("injecting mixtures into %s: %w", def.Name, err)
			}

			body = injected
		}

		result = append(result, SkillDef{
			Name:        def.Name,
			Description: def.Description,
			Body:        body,
		})
	}

	return result, nil
}

func placeForAgent(agent string, extractedSkills []SkillDef, rendered map[string][]byte) ([]PlacedFile, error) {
	switch agent {
	case config.AgentClaude:
		return placeClaude(extractedSkills, rendered)
	case config.AgentCodex:
		return placeCodex(extractedSkills, rendered)
	case config.AgentCopilot:
		return placeCopilot(extractedSkills, rendered)
	case config.AgentCursor:
		return placeCursor(extractedSkills, rendered)
	case config.AgentGemini:
		return placeGemini(extractedSkills, rendered)
	case config.AgentWindsurf:
		return placeWindsurf(extractedSkills, rendered)
	default:
		return nil, fmt.Errorf("unknown agent: %s", agent)
	}
}

// skillMD wraps a skill body with Agent Skills SKILL.md frontmatter.
func skillMD(skill SkillDef) []byte {
	// Pre-compute exact size to avoid Builder reallocations.
	header := "---\nname: " + skill.Name + "\ndescription: " + skill.Description + "\n---\n\n"
	buf := make([]byte, len(header)+len(skill.Body))
	copy(buf, header)
	copy(buf[len(header):], skill.Body)

	return buf
}

// placeClaude generates:
//   - .agents/skills/<name>/SKILL.md  (Agent Skills standard — cross-agent)
//   - .claude/commands/<name>.md       (Claude Code slash commands — legacy compat)
func placeClaude(skills []SkillDef, _ map[string][]byte) ([]PlacedFile, error) {
	// Each skill produces 2 files: .agents/skills/ + .claude/commands/.
	filesPerSkill := 2
	files := make([]PlacedFile, 0, filesPerSkill*len(skills))

	for _, skill := range skills {
		// Agent Skills standard path (works across Claude, Codex, Copilot, Cursor).
		// Claude-specific legacy commands for backward compatibility.
		files = append(files, PlacedFile{
			Path:    filepath.Join(".agents", "skills", skill.Name, "SKILL.md"),
			Content: skillMD(skill),
		}, PlacedFile{
			Path:    filepath.Join(".claude", "commands", skill.Name+".md"),
			Content: skillMD(skill),
		})
	}

	return files, nil
}

// placeCodex generates:
//   - .agents/skills/<name>/SKILL.md  (Agent Skills standard)
func placeCodex(skills []SkillDef, _ map[string][]byte) ([]PlacedFile, error) {
	files := make([]PlacedFile, 0, len(skills))

	for _, skill := range skills {
		files = append(files, PlacedFile{
			Path:    filepath.Join(".agents", "skills", skill.Name, "SKILL.md"),
			Content: skillMD(skill),
		})
	}

	// Codex also reads AGENTS.md natively — no extra placement needed.
	return files, nil
}

// placeCopilot generates:
//   - .agents/skills/<name>/SKILL.md     (Agent Skills standard — Copilot discovers these)
//   - .github/copilot-instructions.md     (Copilot global instructions)
func placeCopilot(skills []SkillDef, rendered map[string][]byte) ([]PlacedFile, error) {
	var files []PlacedFile

	for _, skill := range skills {
		files = append(files, PlacedFile{
			Path:    filepath.Join(".agents", "skills", skill.Name, "SKILL.md"),
			Content: skillMD(skill),
		})
	}

	// Copilot reads a global instructions file.
	if agents, ok := rendered["AGENTS.md"]; ok {
		files = append(files, PlacedFile{
			Path:    filepath.Join(".github", "copilot-instructions.md"),
			Content: agents,
		})
	}

	return files, nil
}

// placeCursor generates:
//   - .agents/skills/<name>/SKILL.md   (Agent Skills standard — Cursor discovers these)
//   - .cursor/rules/agents.mdc          (Cursor rules file from AGENTS.md)
func placeCursor(skills []SkillDef, rendered map[string][]byte) ([]PlacedFile, error) {
	var files []PlacedFile

	for _, skill := range skills {
		files = append(files, PlacedFile{
			Path:    filepath.Join(".agents", "skills", skill.Name, "SKILL.md"),
			Content: skillMD(skill),
		})
	}

	// Cursor reads .cursor/rules/*.mdc with MDC frontmatter.
	if agents, ok := rendered["AGENTS.md"]; ok {
		mdc := wrapMDC("Golang coding agent personality and development workflow", "**/*.go", agents)
		files = append(files, PlacedFile{
			Path:    filepath.Join(".cursor", "rules", "agents.mdc"),
			Content: mdc,
		})
	}

	return files, nil
}

// placeGemini generates:
//   - GEMINI.md                              (Gemini global instructions)
//   - .gemini/commands/<name>.toml            (Gemini TOML commands)
func placeGemini(skills []SkillDef, rendered map[string][]byte) ([]PlacedFile, error) {
	var files []PlacedFile

	// Gemini reads GEMINI.md as its instructions file.
	if agents, ok := rendered["AGENTS.md"]; ok {
		files = append(files, PlacedFile{
			Path:    "GEMINI.md",
			Content: agents,
		})
	}

	// Gemini uses TOML commands, not Markdown.
	for _, skill := range skills {
		toml := skillTOML(skill)
		files = append(files, PlacedFile{
			Path:    filepath.Join(".gemini", "commands", skill.Name+".toml"),
			Content: toml,
		})
	}

	return files, nil
}

// placeWindsurf generates:
//   - .windsurfrules                           (Windsurf global rules from AGENTS.md)
//   - .windsurf/workflows/<name>.md             (Windsurf workflows)
func placeWindsurf(skills []SkillDef, rendered map[string][]byte) ([]PlacedFile, error) {
	var files []PlacedFile

	// Windsurf reads .windsurfrules as its instructions.
	if agents, ok := rendered["AGENTS.md"]; ok {
		files = append(files, PlacedFile{
			Path:    ".windsurfrules",
			Content: agents,
		})
	}

	// Windsurf uses .windsurf/workflows/*.md.
	for _, skill := range skills {
		files = append(files, PlacedFile{
			Path:    filepath.Join(".windsurf", "workflows", skill.Name+".md"),
			Content: skill.Body,
		})
	}

	return files, nil
}

// wrapMDC wraps content in Cursor's MDC format with frontmatter.
func wrapMDC(description, globs string, body []byte) []byte {
	header := "---\ndescription: " + description + "\nglobs: [\"" + globs + "\"]\nalwaysApply: true\n---\n\n"
	buf := make([]byte, len(header)+len(body))
	copy(buf, header)
	copy(buf[len(header):], body)

	return buf
}

// skillTOML converts a skill to Gemini CLI's TOML command format.
func skillTOML(skill SkillDef) []byte {
	descLine := fmt.Sprintf("description = %q\n", skill.Description)

	const (
		prefix = "prompt = \"\"\"\n"
		suffix = "\"\"\"\n"
	)

	needsNewline := len(skill.Body) > 0 && skill.Body[len(skill.Body)-1] != '\n'

	extra := 0
	if needsNewline {
		extra = 1
	}

	capacity := len(descLine) + len(prefix) + len(skill.Body) + extra + len(suffix)
	buf := make([]byte, 0, capacity)
	buf = append(buf, descLine...)
	buf = append(buf, prefix...)
	buf = append(buf, skill.Body...)

	if needsNewline {
		buf = append(buf, '\n')
	}

	buf = append(buf, suffix...)

	return buf
}
